-- Local SQLite schema (source of truth for pharmacy inventory)
-- All monetary values are stored as INTEGER paise (1 INR = 100 paise).
-- All IDs are TEXT UUIDv4, generated by the application before insert.

PRAGMA journal_mode = WAL;
PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS pharmacy (
    id            TEXT PRIMARY KEY,
    name          TEXT NOT NULL,
    owner_name    TEXT NOT NULL,
    phone         TEXT,
    email         TEXT,
    address       TEXT,
    timezone      TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    currency      TEXT NOT NULL DEFAULT 'INR',
    created_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at    TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS users (
    id             TEXT PRIMARY KEY,
    pharmacy_id    TEXT NOT NULL REFERENCES pharmacy(id) ON DELETE CASCADE,
    name           TEXT NOT NULL,
    email          TEXT NOT NULL UNIQUE,
    password_hash  TEXT NOT NULL,        -- Argon2id
    role           TEXT NOT NULL DEFAULT 'owner' CHECK (role IN ('owner','staff')),
    created_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at     TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS medicines (
    id                    TEXT PRIMARY KEY,
    pharmacy_id           TEXT NOT NULL REFERENCES pharmacy(id) ON DELETE CASCADE,
    name                  TEXT NOT NULL,
    generic_name          TEXT,
    brand_name            TEXT,
    category              TEXT,
    manufacturer          TEXT,
    batch_number          TEXT,
    expiry_date           TEXT,                 -- ISO date, nullable
    quantity              INTEGER NOT NULL DEFAULT 0,
    unit                  TEXT NOT NULL DEFAULT 'pcs',
    purchase_price_paise  INTEGER NOT NULL,      -- required
    selling_price_paise   INTEGER,
    minimum_stock_level   INTEGER NOT NULL DEFAULT 0,
    supplier_name         TEXT,
    location              TEXT,
    notes                 TEXT,
    is_deleted            INTEGER NOT NULL DEFAULT 0,  -- soft delete
    created_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
    updated_at            TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_medicines_pharmacy   ON medicines(pharmacy_id);
CREATE INDEX IF NOT EXISTS idx_medicines_name        ON medicines(name);
CREATE INDEX IF NOT EXISTS idx_medicines_generic     ON medicines(generic_name);
CREATE INDEX IF NOT EXISTS idx_medicines_brand       ON medicines(brand_name);
CREATE INDEX IF NOT EXISTS idx_medicines_batch       ON medicines(batch_number);
CREATE INDEX IF NOT EXISTS idx_medicines_manufacturer ON medicines(manufacturer);
CREATE INDEX IF NOT EXISTS idx_medicines_expiry      ON medicines(expiry_date);

CREATE TABLE IF NOT EXISTS inventory_movements (
    id                TEXT PRIMARY KEY,
    medicine_id       TEXT NOT NULL REFERENCES medicines(id) ON DELETE CASCADE,
    type              TEXT NOT NULL CHECK (type IN ('adjustment','initial','import')),
    quantity_before   INTEGER NOT NULL,
    quantity_after    INTEGER NOT NULL,
    reason            TEXT,
    created_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE INDEX IF NOT EXISTS idx_movements_medicine ON inventory_movements(medicine_id);

CREATE TABLE IF NOT EXISTS settings (
    key    TEXT PRIMARY KEY,
    value  TEXT NOT NULL
);

-- Local license cache: the signed token itself is the source of truth,
-- this table just caches it for fast offline startup.
CREATE TABLE IF NOT EXISTS license (
    id                  TEXT PRIMARY KEY DEFAULT 'current',
    license_key         TEXT NOT NULL,
    signed_token        TEXT NOT NULL,      -- Ed25519-signed JWT-like token from cloud
    plan_name            TEXT,
    medicine_limit      INTEGER,
    status              TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','grace','suspended','expired')),
    expiry_date         TEXT,
    grace_period_days   INTEGER NOT NULL DEFAULT 14,
    last_verified_at    TEXT,
    activated_at        TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

-- Default seed settings
INSERT OR IGNORE INTO settings (key, value) VALUES ('expiring_soon_days', '90');
INSERT OR IGNORE INTO settings (key, value) VALUES ('backup_retention_count', '7');
INSERT OR IGNORE INTO settings (key, value) VALUES ('app_version', '1.0.0');
